# check_aws_env.yml

- name: Check if AWS credentials are passed into Ansible
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Print AWS environment variables
      debug:
        msg:
          - "AWS_ACCESS_KEY_ID = {{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
          - "AWS_SECRET_ACCESS_KEY = {{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
          - "AWS_DEFAULT_REGION = {{ lookup('env', 'AWS_DEFAULT_REGION') | default('us-east-1') }}"
